spring.datasource:
   url: jdbc:mysql://localhost:3306/kemao_2?useSSL=false&serverTimezone=CST&allowPublicKeyRetrieval=true
   username: kemao_2
   password: 1234
   driver-class-name: com.mysql.jdbc.Driver
   
   
   
   
   
server.port: 8090
